name = "alleato-ai-chat"
main = "workers/api/index.ts"
compatibility_date = "2024-01-01"

[env.production]
workers_dev = false

# KV Namespaces
[[kv_namespaces]]
binding = "STREAMS"
id = "edb32b0ffbd544dd86afd3841110dc59"

# R2 Buckets
[[r2_buckets]]
binding = "ALLEATO_BUCKET"
bucket_name = "alleato"

# D1 Databases
[[d1_databases]]
binding = "ALLEATO_DB"
database_name = "alleato"
database_id = "fc7c9a6d-ca65-4768-b3f9-07ec5afb38c5"

# Environment Variables
[vars]
R2_PUBLIC_URL = "https://pub-9d242043d9cd491095cb8e4b2e7b8bfc.r2.dev"
WORKER_TOKEN = "ebUZUTmbkRF+Np4i56VgdWgFcP/K0uxHT/ekZeTRP+g="